#15 모델 설계
be-you-and-me/be-you pull request #18
Opened 2021-10-05 09:22 UTC by jryoun1

## Description

<img width="828" alt="image" src="https://user-images.githubusercontent.com/45090197/135995082-0774a9ab-c64e-4ae9-8e59-44c0020f45f5.png">

- be-you app에서 사용할 모델을 작성
- 기획이 완료되면 코드로 구현 예정

#### Reference(issue number)

#15 

#### Changes

- User 타입을 Singleton이 아닌 UserDefualts를 사용하기로함
- Days 타입을 Singleton이 아닌 각 화면에서 가지도록 하기로함 

### Note(Optional)

- 기획과 상의하여 한 번에 불러오는 날들의 개수를 파악하고 수정할 예정
- CoreData를 사용하기 때문에 CoreData를 Combine을 활용하여 사용할 수 있도록 구축 예정

### Check List

- [x] title에 이슈 번호 (ex. #number 000 적용)

- [x] build 확인

- [x] assignees 지정

- [x] Labels 지정

- [x] Milestone 지정

2021-10-05 12:11 UTC, wonhee009 requested changes

2021-10-05 12:11 UTC, wonhee009 commented on Model.md
> +	var date: Date()
왜 Date를 생성해주는거죠?

2021-10-05 12:11 UTC, wonhee009 commented on Model.md
> +	var color: String?
color를 String으로 받나요?

2021-10-05 12:11 UTC, wonhee009 commented on Model.md
> +}
struct로 한 이유가 있나여?

2021-10-05 12:11 UTC, wonhee009 commented on Model.md
> +}
Emotion은 컬러칩에 관해서 정의한거 같은데요.... 흠 뭔가 더 좋은 방식이 없을까요

2021-10-05 13:08 UTC, jryoun1 commented on Model.md
> +	var date: Date()
`Day` 타입에서 `date`를 제외한 나머지 프로퍼티들은 사용자로부터 입력을 받을수도 있고 받지 않을 수 있는 값이라서 옵셔널로 두었고, `date`의 경우에는 사용자가 설정하지 않아도 기본적으로 설정 되어야한다고 생각해서 Date()로 초기화해줬습니다.

`var date: Date = Date()` 로 변경했어요!

2021-10-05 13:09 UTC, jryoun1 commented on Model.md
> +	var color: String?
`UIColor`로 수정했습니다

2021-10-06 04:49 UTC, wonhee009 approved these changes

2021-10-07 15:50 UTC, merged